
version: '3.8'

services:
  app:
    build: .
    container_name: langchain_backend
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=langchain_db
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: langchain_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: langchain_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7.0
    container_name: langchain_redis
    ports:
      - "6379:6379"

volumes:
  db_data:
